# Generated by Django 5.1.1 on 2024-09-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('rate_per_kwh', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
        ),
    ]
